spring.application.name=p1-gateway
server.port=8080

spring.cloud.kubernetes.namespace=reboot-patterns
spring.cloud.kubernetes.discovery.all-namespaces=false

spring.cloud.gateway.httpclient.response-timeout=5s

management.server.port=8081
management.endpoints.web.exposure.include=health,prometheus
management.metrics.export.prometheus.enabled=true

logging.config=classpath:logback-spring.xml
